font_family DejaVu Sans Mono
font_size 12.0

background #0b0614
foreground #ede7f6
cursor #d946ef
selection_background #4c1d95

background_opacity 0.92
window_padding_width 12

color0 #0b0614
color1 #f472b6
color2 #c084fc
color3 #ddd6fe
color4 #8a7cff
color5 #d946ef
color6 #a78bfa
color7 #ede7f6

color8 #6d5a7a
color9 #ff79c6
color10 #c084fc
color11 #e9d5ff
color12 #b39ddb
color13 #f0abfc
color14 #ce93d8
color15 #ffffff

# Lila Tab-Leiste
tab_bar_style powerline
tab_powerline_style slanted

active_tab_foreground #ffffff
active_tab_background #7c3aed
active_tab_font_style bold

inactive_tab_foreground #ede7f6
inactive_tab_background #2e1065
inactive_tab_font_style normal

tab_bar_background #1a102b
